services:
  nginx:
    image: docker6617/nginx-lb01:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    hostname: nginx-lb01

  # backends:
  echo1:
    image: weshigbee/nginx-echo
    ports:
      - "8000:8080"
    hostname: echo1
  echo2:
    image: weshigbee/nginx-echo
    hostname: echo2
  echo3:
    image: weshigbee/nginx-echo
    hostname: echo3
